---

- name: Get secret definition from pvc
  community.kubernetes.k8s_exec:
    namespace: "{{ tower_backup_pvc_namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "cat '{{ tower_backup_dir }}/{{ item }}.yml'"
  register: awx_object

- name: Write temp secret definition template file
  copy:
    dest: "_definitions/{{ item }}.yml.j2"
    content: |
      {{ awx_object.stdout }}
    mode: '0600'

- name: Apply secret
  k8s:
    state: "{{ state | default('present') }}"
    namespace: "{{ namespace | default('default') }}"
    apply: yes
    wait: yes
    template: "_definitions/{{ item }}.yml.j2"
