---

- name: Delete any existing management pod
  community.kubernetes.k8s:
    name: "{{ meta.name }}-db-management"
    kind: Pod
    namespace: "{{ meta.namespace }}"
    state: absent
    force: true
