---

- name: Look up details for this restore object
  k8s_info:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
  register: this_restore

- block:
    - include_tasks: init.yml

    - include_tasks: secrets.yml

    - include_tasks: deploy_awx.yml

    - include_tasks: postgres.yml

    - name: Set flag signifying this restore was successful
      set_fact:
        tower_restore_complete: True

    - include_tasks: cleanup.yml

  when:
    - this_restore['resources'][0]['status']['towerRestoreComplete'] is not defined

- name: Update status variables
  include_tasks: update_status.yml
