---

# Check to make sure provided pvc exists, error loudly if not.  Otherwise, the management pod will just stay in pending state forever.
- name: Check provided PVC exists
  k8s_info:
    name: "{{ tower_backup_pvc }}"
    kind: PersistentVolumeClaim
    namespace: "{{ meta.namespace }}"
  register: provided_pvc
  when:
    - tower_backup_pvc != ''

- name: Surface error to user
  block:
    - name: Set error message
      set_fact:
        error_msg: "{{ tower_backup_pvc }} does not exist, please create this pvc first."

    - name: Handle error
      import_tasks: error_handling.yml

    - name: Fail early if pvc is defined but does not exist
      fail:
        msg: "{{ tower_backup_pvc }} does not exist, please create this pvc first."
  when:
    - tower_backup_pvc != ''
    - provided_pvc.resources | length == 0
