---

- name: Create secret_key secret
  k8s:
    definition: "{{ lookup('file', '/'.join([tower_backup_dir, 'secret_key_secret.yml'])) }}"

- name: Create admin_password secret
  k8s:
    definition: "{{ lookup('file', '/'.join([tower_backup_dir, 'admin_password_secret.yml'])) }}"

- name: Create broadcast_websocket secret
  k8s:
    definition: "{{ lookup('file', '/'.join([tower_backup_dir, 'broadcast_websocket_secret.yml'])) }}"

- name: Create postgres configuration secret
  k8s:
    definition: "{{ lookup('file', '/'.join([tower_backup_dir, 'postgres_secret.yml'])) }}"

- name: Create secret_key secret
  k8s:
    definition: "{{ lookup('file', '/'.join([tower_backup_dir, 'secret_key_secret.yml'])) }}"
