---

- name: Set AWX object
  set_fact:
    _awx: "{{ this_awx['resources'][0] }}"

- name: Set user specified spec
  set_fact:
    awx_spec: "{{ _awx['spec'] }}"

- name: Write awx object to pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "echo '{{ awx_spec }}' > {{ backup_dir }}/awx_object"
