---

- name: Get AWX custom resource object
  k8s_info:
    version: v1beta1
    kind: AWX
    namespace: '{{ meta.namespace }}'
    name: '{{ deployment_name }}'
  register: _awx_cro

- name: Set AWX object
  set_fact:
    _awx: "{{ _awx_cro['resources'][0] }}"

- name: Set user specified spec
  set_fact:
    awx_spec: "{{ _awx['spec'] }}"

- name: Set names of backed up secrets in the CR spec
  set_fact:
    awx_spec: "{{ awx_spec | combine ({ item.key : item.value }) }}"
  with_items:
    - {"key": "secret_key_secret", "value": "{{ this_awx['resources'][0]['status']['secretKeySecret'] }}"}
    - {"key": "admin_password_secret", "value": "{{ this_awx['resources'][0]['status']['adminPasswordSecret'] }}"}
    - {"key": "broadcast_websocket_secret", "value": "{{ this_awx['resources'][0]['status']['broadcastWebsocketSecret'] }}"}
    - {"key": "postgres_configuration_secret", "value": "{{ this_awx['resources'][0]['status']['postgresConfigurationSecret'] }} "}

# TODO: REMOVE ME
- copy:
    dest: "test-spec.txt"
    content: "{{ awx_spec | to_yaml }}"

- name: Nest secrets under a single variable
  set_fact:
    definitions: {"awx_spec": '{{ awx_spec | quote }}'}
