---

- include_tasks: init.yml

- include_tasks: postgres.yml

- include_tasks: secrets.yml

# TODO: Add task to change the status on the backup CR when this runs successfully
- name: Set flag signifying this backup was successful
  set_fact:
    tower_backup_complete: "{{ _backup_dir }}"


- include_tasks: cleanup.yml
