---
- name: Deploy an instance of AWX using the awx-operator
  hosts: localhost

  collections:
    - community.kubernetes

  tasks:
    - name: Deploy AWX
      k8s:
        state: "{{ state | default('present') }}"
        namespace: "{{ namespace | default('default') }}"
        apply: yes
        wait: yes
        definition:
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
          spec:
            tower_admin_user: test
            tower_admin_email: test@example.com
            tower_ingress_type: "{{ tower_ingress_type | default(omit) }}"  # Either Route, Ingress or LoadBalancer
            tower_image: "{{ tower_image | default(omit) }}"
            development_mode: "{{ (development_mode|bool) | default(omit) }}"
            tower_image_pull_policy: "{{ tower_image_pull_policy | default(omit) }}"
