---
name: Promote AWX Operator image
on:
  - workflow_dispatch
  # release:
  #     types: [published]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Log in to Quay
        run: |
          echo ${{ secrets.QUAY_TOKEN }} | docker login quay.io -u ${{ secrets.QUAY_USER }} --password-stdin

      - name: Re-tag and promote awx-operator image
        run: |
          docker pull ghcr.io/${{ github.repository }}:1.1.3-test
          docker tag ghcr.io/${{ github.repository }}:1.1.3-test quay.io/chadams/awx-operator:1.1.3-test
          docker tag ghcr.io/${{ github.repository }}:1.1.3-test quay.io/chadams/awx-operator:latest
          docker push quay.io/chadams/awx-operator:1.1.3-test
          docker push quay.io/chadams/awx-operator:latest

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release Helm chart
        run: |
          ansible-playbook ansible/helm-release.yml -v \
            -e operator_image=quay.io/chadams/awx-operator \
            -e chart_owner=${{ github.repository_owner }} \
            -e tag=1.1.3-test \
            -e gh_token=${{ secrets.GITHUB_TOKEN }}
