---
name: Translate Readme

on:
  push:
    branches: [devel]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Adding README
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr  # French

      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: es  # Spanish

      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja  # Japanese

      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN  # Simplified Chinese
